server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        boostrap: false
        git:
          uri: https://github.com/syd-studycase/inghubs-java-case-study
          search-paths: configs
          clone-on-start: true
          default-label: main
          username: syd_studycase
          password: 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

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true