spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/orders/**
        - id: asset
          uri: lb://asset
          predicates:
            - Path=/api/v1/assets/**
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
