spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/orders/**
        - id: asset
          uri: lb://asset
          predicates:
            - Path=/api/v1/assets/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/inghubs
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: order
        url: /aggregate/order/v3/api-docs
      - name: asset
        url: /aggregate/asset/v3/api-docs
  api-docs:
    path: /api-docs



